// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface InvoiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.InvoiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string invoiceID = 1;</code>
   */
  java.lang.String getInvoiceID();
  /**
   * <code>string invoiceID = 1;</code>
   */
  com.google.protobuf.ByteString
      getInvoiceIDBytes();

  /**
   * <code>string confirmMessage = 2;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();
}
