// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmMessage = 1;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();
}
