// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double payment = 1;</code>
   */
  double getPayment();
}
