// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface RefundsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.RefundsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string refundID = 1;</code>
   */
  java.lang.String getRefundID();
  /**
   * <code>string refundID = 1;</code>
   */
  com.google.protobuf.ByteString
      getRefundIDBytes();

  /**
   * <code>string confirmMessage = 2;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();
}
