// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface RefundsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.RefundsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerName = 1;</code>
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customerName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string rideID = 2;</code>
   */
  java.lang.String getRideID();
  /**
   * <code>string rideID = 2;</code>
   */
  com.google.protobuf.ByteString
      getRideIDBytes();

  /**
   * <code>double amount = 3;</code>
   */
  double getAmount();
}
