// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PaymentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_InvoiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_InvoiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_InvoiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_InvoiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_RefundsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_RefundsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_RefundsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_RefundsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"!\n\016PaymentReq" +
      "uest\022\017\n\007payment\030\001 \001(\001\")\n\017PaymentResponse" +
      "\022\026\n\016confirmMessage\030\001 \001(\t\"6\n\016InvoiceReque" +
      "st\022\024\n\014customerName\030\001 \001(\t\022\016\n\006amount\030\002 \001(\001" +
      "\"<\n\017InvoiceResponse\022\021\n\tinvoiceID\030\001 \001(\t\022\026" +
      "\n\016confirmMessage\030\002 \001(\t\"F\n\016RefundsRequest" +
      "\022\024\n\014customerName\030\001 \001(\t\022\016\n\006rideID\030\002 \001(\t\022\016" +
      "\n\006amount\030\003 \001(\001\";\n\017RefundsResponse\022\020\n\010ref" +
      "undID\030\001 \001(\t\022\026\n\016confirmMessage\030\002 \001(\t2\362\001\n\r" +
      "PaymentSystem\022G\n\016processPayment\022\030.servic" +
      "e3.PaymentRequest\032\031.service3.PaymentResp" +
      "onse\"\000\022L\n\017generateInvoice\022\030.service3.Inv" +
      "oiceRequest\032\031.service3.InvoiceResponse\"\000" +
      "(\0010\001\022J\n\rhandleRefunds\022\030.service3.Refunds" +
      "Request\032\031.service3.RefundsResponse\"\000(\0010\001" +
      "B\035\n\013ds.service3B\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PaymentRequest_descriptor,
        new java.lang.String[] { "Payment", });
    internal_static_service3_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PaymentResponse_descriptor,
        new java.lang.String[] { "ConfirmMessage", });
    internal_static_service3_InvoiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_InvoiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_InvoiceRequest_descriptor,
        new java.lang.String[] { "CustomerName", "Amount", });
    internal_static_service3_InvoiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_InvoiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_InvoiceResponse_descriptor,
        new java.lang.String[] { "InvoiceID", "ConfirmMessage", });
    internal_static_service3_RefundsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_RefundsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_RefundsRequest_descriptor,
        new java.lang.String[] { "CustomerName", "RideID", "Amount", });
    internal_static_service3_RefundsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_RefundsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_RefundsResponse_descriptor,
        new java.lang.String[] { "RefundID", "ConfirmMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
