// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentLocation = 1;</code>
   */
  java.lang.String getCurrentLocation();
  /**
   * <code>string currentLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentLocationBytes();

  /**
   * <code>string destination = 2;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
