// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmMessage = 1;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();
}
