// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.InfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rideID = 1;</code>
   */
  java.lang.String getRideID();
  /**
   * <code>string rideID = 1;</code>
   */
  com.google.protobuf.ByteString
      getRideIDBytes();
}
