// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startingLocation = 1;</code>
   */
  java.lang.String getStartingLocation();
  /**
   * <code>string startingLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartingLocationBytes();

  /**
   * <code>string destination = 2;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
