// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_InfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\";\n\013BookReques" +
      "t\022\027\n\017currentLocation\030\001 \001(\t\022\023\n\013destinatio" +
      "n\030\002 \001(\t\"&\n\014BookResponse\022\026\n\016confirmMessag" +
      "e\030\001 \001(\t\"\037\n\rCancelRequest\022\016\n\006rideID\030\001 \001(\t" +
      "\" \n\016CancelResponse\022\016\n\006status\030\001 \001(\t\"\035\n\013In" +
      "foRequest\022\016\n\006rideID\030\001 \001(\t\"=\n\014InfoRespons" +
      "e\022\030\n\020startingLocation\030\001 \001(\t\022\023\n\013destinati" +
      "on\030\002 \001(\t2\325\001\n\017CustomerService\022=\n\010bookRide" +
      "\022\025.service2.BookRequest\032\026.service2.BookR" +
      "esponse\"\000(\001\022A\n\ncancelRide\022\027.service2.Can" +
      "celRequest\032\030.service2.CancelResponse\"\000\022@" +
      "\n\013getRideInfo\022\025.service2.InfoRequest\032\026.s" +
      "ervice2.InfoResponse\"\0000\001B\035\n\013ds.service2B" +
      "\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BookRequest_descriptor,
        new java.lang.String[] { "CurrentLocation", "Destination", });
    internal_static_service2_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BookResponse_descriptor,
        new java.lang.String[] { "ConfirmMessage", });
    internal_static_service2_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CancelRequest_descriptor,
        new java.lang.String[] { "RideID", });
    internal_static_service2_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CancelResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_service2_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_InfoRequest_descriptor,
        new java.lang.String[] { "RideID", });
    internal_static_service2_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_InfoResponse_descriptor,
        new java.lang.String[] { "StartingLocation", "Destination", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
