// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vehicleID = 1;</code>
   */
  java.lang.String getVehicleID();
  /**
   * <code>string vehicleID = 1;</code>
   */
  com.google.protobuf.ByteString
      getVehicleIDBytes();
}
