// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string targetCapacity = 1;</code>
   */
  java.lang.String getTargetCapacity();
  /**
   * <code>string targetCapacity = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetCapacityBytes();
}
