// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string targetCapacity = 1;</code>
   */
  java.lang.String getTargetCapacity();
  /**
   * <code>string targetCapacity = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetCapacityBytes();

  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */

  java.lang.String getHeadersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */

  java.lang.String getHeadersOrThrow(
      java.lang.String key);
}
