// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AddRequest_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AddRequest_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RemoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RemoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RemoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RemoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"\210\001\n\nAddReques" +
      "t\022\026\n\016targetCapacity\030\001 \001(\t\0222\n\007headers\030\003 \003" +
      "(\0132!.service1.AddRequest.HeadersEntry\032.\n" +
      "\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\" \n\013AddResponse\022\021\n\tvehicleID\030\001 \001(\t\"" +
      "!\n\rRemoveRequest\022\020\n\010capacity\030\001 \001(\t\"#\n\016Re" +
      "moveResponse\022\021\n\tvehicleID\030\001 \001(\t\"\"\n\rStatu" +
      "sRequest\022\021\n\tvehicleID\030\001 \001(\t\"?\n\016StatusRes" +
      "ponse\022\027\n\017currentLocation\030\001 \001(\t\022\024\n\014curren" +
      "tSpeed\030\002 \001(\t2\337\001\n\017FleetManagement\022;\n\naddV" +
      "ehicle\022\024.service1.AddRequest\032\025.service1." +
      "AddResponse\"\000\022D\n\rremoveVehicle\022\027.service" +
      "1.RemoveRequest\032\030.service1.RemoveRespons" +
      "e\"\000\022I\n\020getVehicleStatus\022\027.service1.Statu" +
      "sRequest\032\030.service1.StatusResponse\"\0000\001B\035" +
      "\n\013ds.service1B\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AddRequest_descriptor,
        new java.lang.String[] { "TargetCapacity", "Headers", });
    internal_static_service1_AddRequest_HeadersEntry_descriptor =
      internal_static_service1_AddRequest_descriptor.getNestedTypes().get(0);
    internal_static_service1_AddRequest_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AddRequest_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_service1_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AddResponse_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_RemoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_RemoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RemoveRequest_descriptor,
        new java.lang.String[] { "Capacity", });
    internal_static_service1_RemoveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_RemoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RemoveResponse_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StatusRequest_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StatusResponse_descriptor,
        new java.lang.String[] { "CurrentLocation", "CurrentSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
