// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RemoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RemoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RemoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RemoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"$\n\nAddRequest" +
      "\022\026\n\016targetCapacity\030\001 \001(\t\" \n\013AddResponse\022" +
      "\021\n\tvehicleID\030\001 \001(\t\"!\n\rRemoveRequest\022\020\n\010c" +
      "apacity\030\001 \001(\t\"#\n\016RemoveResponse\022\021\n\tvehic" +
      "leID\030\001 \001(\t\"\"\n\rStatusRequest\022\021\n\tvehicleID" +
      "\030\001 \001(\t\"?\n\016StatusResponse\022\027\n\017currentLocat" +
      "ion\030\001 \001(\t\022\024\n\014currentSpeed\030\002 \001(\t2\337\001\n\017Flee" +
      "tManagement\022;\n\naddVehicle\022\024.service1.Add" +
      "Request\032\025.service1.AddResponse\"\000\022D\n\rremo" +
      "veVehicle\022\027.service1.RemoveRequest\032\030.ser" +
      "vice1.RemoveResponse\"\000\022I\n\020getVehicleStat" +
      "us\022\027.service1.StatusRequest\032\030.service1.S" +
      "tatusResponse\"\0000\001B\035\n\013ds.service1B\014Servic" +
      "e1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AddRequest_descriptor,
        new java.lang.String[] { "TargetCapacity", });
    internal_static_service1_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AddResponse_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_RemoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_RemoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RemoveRequest_descriptor,
        new java.lang.String[] { "Capacity", });
    internal_static_service1_RemoveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_RemoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RemoveResponse_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StatusRequest_descriptor,
        new java.lang.String[] { "VehicleID", });
    internal_static_service1_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StatusResponse_descriptor,
        new java.lang.String[] { "CurrentLocation", "CurrentSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
