// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentLocation = 1;</code>
   */
  java.lang.String getCurrentLocation();
  /**
   * <code>string currentLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentLocationBytes();

  /**
   * <code>string currentSpeed = 2;</code>
   */
  java.lang.String getCurrentSpeed();
  /**
   * <code>string currentSpeed = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentSpeedBytes();
}
